steps:


  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']

  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']
    
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pytest', '--junitxml=${SHORT_SHA}_test_log.xml']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/terraform-gcp-402419/latam-challenge/pyspark-jupyter:917376'
      - '.'
    # Step 1: Docker Build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/terraform-gcp-402419/latam-challenge/pyspark-jupyter:917376'
    # Step 3: Docker Push to Artifact Registry
