steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'terraform-gcp-402419/latam-challenge/pyspark-jupyter:917376', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'terraform-gcp-402419/latam-challenge/pyspark-jupyter:917376', '.']
images: ['terraform-gcp-402419/latam-challenge/pyspark-jupyter:917376']
